# Site settings
title: Jorden runt
email: stormtrivs@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  En sida om programmering, segling och äventyr. Vilka datorsystem används vid navigering och
  hur fungerar väderdata? Hur kan programmering få en plats i kommande äventyr?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: stormtrivs
github_username:  stormtrivs

# Build settings
markdown: kramdown
